plugins {
    id 'fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'

    id "com.modrinth.minotaur" version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.+'
    id "com.github.breadmoirai.github-release" version "2.5.2"
}

import com.modrinth.minotaur.dependencies.ModDependency
import net.darkhax.curseforgegradle.TaskPublishCurseForge

base {
    archivesName = project.archives_base_name
}
version = project.mod_version + '-' + project.minecraft_version
group = project.maven_group

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.

    // Mods on Modrinth
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    // Mod Menu 模组
    maven { url 'https://maven.terraformersmc.com/releases/' }
    maven { url 'https://jitpack.io' }


    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}


dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    if (project.hasProperty('imblocker_version') && !project.imblocker_version.isEmpty()) {
        modRuntimeOnly "maven.modrinth:imblocker-original:$project.imblocker_version"
    }

    // 仅供在模组开发时测试与光影的兼容
    modRuntimeOnly "maven.modrinth:sodium:mc1.21.8-0.7.3-fabric"
    modRuntimeOnly "maven.modrinth:iris:1.9.6+1.21.8-fabric"
    modImplementation("org.antlr:antlr4-runtime:4.13.1")
    modImplementation("io.github.douira:glsl-transformer:3.0.0-pre3")
    modImplementation("org.anarres:jcpp:1.4.14")
}

processResources {
    inputs.property "version", project.mod_version

    filesMatching("fabric.mod.json") {
        expand "version": project.mod_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }


    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}



loom {
    runs {
        client {
            programArg "-username=Solid"
        }
    }
}

/**
 * 从 UpdateLog-en.md 中提取更新日志
 */
String getUpdateLog(String modVersion = project.mod_version) {
    StringBuilder builder = new StringBuilder()
    boolean start = false
    new File('UpdateLog-en.md').eachLine {
        if (it.matches("^###\\s*" + modVersion + '$')) {
            start = true
        } else if (it.startsWith("###")) {
            start = false
        } else if (start) {
            builder.append it
            builder.append '\n'
        }
        return
    }
    return builder.toString().trim()
}

// 模组发布部分

println "当前版本（${project.mod_version}）更新记录："
final var content = getUpdateLog(project.mod_version)
println content

tasks.register('curseforge', TaskPublishCurseForge) {
    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
    println("CurseForge 令牌: ${curseforgeToken instanceof String ? curseforgeToken.replaceAll("^(.+?)(.{0,6})\$", (s, a, b) -> a.replaceAll(".", "*") + b) : curseforgeToken}")
    if (curseforgeToken) apiToken = curseforgeToken

    def mainFile = upload('583071', remapJar)
    mainFile.changelog = content
    mainFile.changelogType = 'markdown'
    mainFile.releaseType = project.mod_version.contains('-') ? 'beta' : 'release'

    for (final def v in ((project.supported_minecraft_versions as String).split(','))) {
        mainFile.addGameVersion v
    }

    mainFile.addEnvironment 'Client', 'Server'

    mainFile.addRelations 'requiredDependency', 'fabric-api'
    mainFile.withAdditionalFile(sourcesJar)
}

modrinth {
    println "Modrinth 令牌：${token.get() instanceof String ? token.get().replaceAll("^(.+?)(.{0,6})\$", (s, a, b) -> a.replaceAll(".", "*") + b) : token.get()}"

    projectId = "rItLmRo4" // 迷上城建模组的 Modrinth ID
    versionNumber = project.mod_version + '-' + project.minecraft_version
    versionType = project.mod_version.contains('-') ? 'beta' : 'release'  // until release of MC
    uploadFile = remapJar
    gameVersions = Arrays.asList(project.supported_minecraft_versions.split(','))

    changelog = content

    loaders = ['fabric']

    dependencies = [
            new ModDependency('P7dR8mSH', 'required'), // Fabric API
    ]
}

githubRelease {
    def githubToken = System.getenv("GITHUB_TOKEN")
    println "GitHub 令牌: ${githubToken instanceof String ? githubToken.replaceAll("^(.+?)(.{0,6})\$", (s, a, b) -> a.replaceAll(".", "*") + b) : githubToken}"
    if (githubToken) token = githubToken
    owner = "SolidBlock-cn"
    repo = "mishanguc"
    tagName = "v$project.mod_version"
    targetCommitish = "1.21.8"
    body = content
    draft = true
    prerelease = false
    releaseAssets remapJar, remapSourcesJar
    allowUploadToExisting = true
    apiEndpoint = "https://api.github.com"
}

publish {
    dependsOn tasks.curseforge, tasks.modrinth, tasks.githubRelease
}

fabricApi {
    configureDataGeneration() {
        client = true
    }
}